"""Generate a Stonefish 1.6 pool with exact interior dimensions in NED coordinates."""

import argparse
import math
import xml.etree.ElementTree as ET
from dataclasses import dataclass, fields
from pathlib import Path

import yaml


@dataclass(frozen=True)
class PoolConfig:
    length: float = 25.0
    width: float = 15.0
    depth: float = 3.0
    wall_thickness: float = 0.3
    floor_thickness: float = 0.3
    freeboard: float = 0.3
    water_density: float = 1000.0
    water_temperature: float = 26.0
    jerlov: float = 0.05
    sun_azimuth: float = 120.0
    sun_elevation: float = 75.0
    latitude: float = 36.0014
    longitude: float = -78.9382

    def __post_init__(self):
        for field in fields(self):
            value = getattr(self, field.name)
            if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value):
                raise ValueError(f'{field.name} must be a finite number')
        for name in ('length', 'width', 'depth', 'wall_thickness', 'floor_thickness', 'water_density'):
            if getattr(self, name) <= 0:
                raise ValueError(f'{name} must be positive')
        if self.freeboard < 0:
            raise ValueError('freeboard must be nonnegative')
        for name, lower, upper in (
            ('jerlov', 0, 1),
            ('latitude', -90, 90),
            ('longitude', -180, 180),
            ('sun_azimuth', 0, 360),
            ('sun_elevation', -90, 90),
        ):
            if not lower <= getattr(self, name) <= upper:
                raise ValueError(f'{name} must be in [{lower}, {upper}]')


def load_config(path: Path, **overrides: float) -> PoolConfig:
    with path.open(encoding='utf-8') as stream:
        values = yaml.safe_load(stream)
    if not isinstance(values, dict):
        raise ValueError('Pool configuration must be a YAML mapping')
    unknown = values.keys() - {field.name for field in fields(PoolConfig)}
    if unknown:
        raise ValueError(f'Unknown pool settings: {", ".join(sorted(unknown))}')
    return PoolConfig(**(values | overrides))


def _vector(values):
    return ' '.join(format(value, '.12g') for value in values)


def build_scenario(config: PoolConfig) -> ET.ElementTree:
    root = ET.Element('scenario')
    root.append(
        ET.Comment('Generated by robosub_simulation.pool. World origin: pool centre at water surface; +Z down.')
    )
    environment = ET.SubElement(root, 'environment')
    ET.SubElement(environment, 'ned', latitude=str(config.latitude), longitude=str(config.longitude))
    ocean = ET.SubElement(environment, 'ocean')
    ET.SubElement(
        ocean,
        'water',
        density=str(config.water_density),
        temperature=str(config.water_temperature),
        jerlov=str(config.jerlov),
    )
    ET.SubElement(ocean, 'waves', height='0.0')
    ET.SubElement(ocean, 'particles', enabled='false')
    atmosphere = ET.SubElement(environment, 'atmosphere')
    ET.SubElement(atmosphere, 'sun', azimuth=str(config.sun_azimuth), elevation=str(config.sun_elevation))

    materials = ET.SubElement(root, 'materials')
    ET.SubElement(materials, 'material', name='pool_concrete', density='2300.0', restitution='0.1')
    friction = ET.SubElement(materials, 'friction_table')
    ET.SubElement(
        friction, 'friction', material1='pool_concrete', material2='pool_concrete', static='0.8', dynamic='0.6'
    )
    looks = ET.SubElement(root, 'looks')
    ET.SubElement(looks, 'look', name='pool_floor', rgb='0.85 0.90 0.92', roughness='0.65', metalness='0.0')
    ET.SubElement(looks, 'look', name='pool_wall', rgb='0.35 0.65 0.80', roughness='0.6', metalness='0.0')

    length, width, depth = config.length, config.width, config.depth
    wall, floor = config.wall_thickness, config.floor_thickness
    height = depth + config.freeboard
    wall_z = (depth - config.freeboard) / 2
    boxes = [
        ('pool_floor', (length + 2 * wall, width + 2 * wall, floor), (0, 0, depth + floor / 2)),
        ('pool_wall_north', (wall, width + 2 * wall, height), ((length + wall) / 2, 0, wall_z)),
        ('pool_wall_south', (wall, width + 2 * wall, height), (-(length + wall) / 2, 0, wall_z)),
        ('pool_wall_east', (length, wall, height), (0, (width + wall) / 2, wall_z)),
        ('pool_wall_west', (length, wall, height), (0, -(width + wall) / 2, wall_z)),
    ]
    for name, dimensions, position in boxes:
        body = ET.SubElement(root, 'static', name=name, type='box')
        ET.SubElement(body, 'dimensions', xyz=_vector(dimensions))
        ET.SubElement(body, 'material', name='pool_concrete')
        ET.SubElement(body, 'look', name='pool_floor' if name == 'pool_floor' else 'pool_wall')
        ET.SubElement(body, 'world_transform', xyz=_vector(position), rpy='0 0 0')
    ET.indent(root, space='  ')
    return ET.ElementTree(root)


def write_scenario(config: PoolConfig, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    build_scenario(config).write(path, encoding='utf-8', xml_declaration=True)
    return path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--config', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    for name in ('length', 'width', 'depth'):
        parser.add_argument(f'--{name}', type=float)
    args = parser.parse_args()
    overrides = {name: getattr(args, name) for name in ('length', 'width', 'depth') if getattr(args, name) is not None}
    try:
        config = load_config(args.config, **overrides)
        write_scenario(config, args.output)
    except (OSError, ValueError, TypeError, yaml.YAMLError) as error:
        parser.error(str(error))
    print(f'Wrote {args.output}: {config.length:g} x {config.width:g} x {config.depth:g} m pool')


if __name__ == '__main__':
    main()
